services:
  mongodb:
    image: mongo
    container_name: volunteer-db-container
    ports:
      - "27017:27017"
  data-importer:
    image: mongo
    volumes:
      - ./docker_files/database/volunteers.json:/volunteers.json
    command: sh -c "mongoimport --host mongodb --db volunteers_db --collection shifts --type json --file /volunteers.json --jsonArray"
    depends_on:
      - mongodb
     
  backend:
    build:
      context: ./server
      dockerfile: ../docker_files/server/Dockerfile
    environment:
      FLASK_ENV: development
      FLASK_CONFIG: development
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: volunteers_db
      GOOGLE_CLIENT_ID: 214227450442-gp12srosdps9365qbfum19dvnutu9gi5.apps.googleusercontent.com
      JWT_SECRET: local-docker-development-secret
    ports:
      - "5001:5001"
    depends_on:
      - mongodb

  frontend:
    build: 
      context: ./client_app
      dockerfile: ../docker_files/client_app/Dockerfile
    environment:
      REACT_APP_SERVER_URL: http://localhost:5001
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: client_app/package.json
          action: rebuild
        - path: client_app/
          target: /usr/src/app
          action: sync
    depends_on:
      - backend 
  

  

  
