// mock shelter data response
export const shelterData = {
    "totalElements": 3,
    "totalPages": 1,
    "pageable": {
      "pageNumber": 0,
      "pageSize": 3,
      "sort": {
        "unsorted": true,
        "sorted": false,
        "empty": true
      },
      "offset": 0,
      "unpaged": false,
      "paged": true
    },
    "numberOfElements": 138,
    "first": true,
    "last": true,
    "size": 1000,
    "content": [
      {
        "id": 111,
        "facilityType": "shelter",
        "status": 0,
        "name": "test shelter 1",
        "organizationId": null,
        "phone": "(620) 221-9664",
        "website": null,
        "city": "Winfield",
        "state": "KS",
        "county": "Cowley",
        "country": "usa",
        "zipCode": "67156",
        "latitude": 37.16481,
        "longitude": -97.026717,
        "privateAddress": false,
        "beds": 0,
        "baths": null,
        "favorite": null,
        "accreditations": [],
        "images": [],
        "distance": 11.4821168240232,
        "residentServed": "POP_UNDER_18,POP_18_65,POP_FEMALE_ONLY,POP_MALE_ONLY",
        "genderType": null,
        "acceptsInsurance": true,
        "avgCostMinimum": null,
        "depositAmount": null,
        "rentPaidWeekly": null,
        "moudMedications": null,
        "smokingPolicy": "PT_TOBACCO_ALLOWED_DESIGNATED",
        "bedUpdatedAt": null,
        "structureType": null,
        "volunteerNeeded": false,
        "volunteerCapacity": null,
        "volunteerCount": null
      },
      {
        "id": 222,
        "facilityType": "shelter",
        "status": 0,
        "name": "test shelter 2",
        "organizationId": null,
        "phone": "(620) 221-9664",
        "website": null,
        "city": "Winfield",
        "state": "KS",
        "county": "Cowley",
        "country": "usa",
        "zipCode": "67156",
        "latitude": 37.16481,
        "longitude": -97.026717,
        "privateAddress": false,
        "beds": 0,
        "baths": null,
        "favorite": null,
        "accreditations": [],
        "images": [],
        "distance": 11.4821168240232,
        "residentServed": "POP_UNDER_18,POP_18_65,POP_FEMALE_ONLY,POP_MALE_ONLY",
        "genderType": null,
        "acceptsInsurance": true,
        "avgCostMinimum": null,
        "depositAmount": null,
        "rentPaidWeekly": null,
        "moudMedications": null,
        "smokingPolicy": "PT_TOBACCO_ALLOWED_DESIGNATED",
        "bedUpdatedAt": null,
        "structureType": null,
        "volunteerNeeded": false,
        "volunteerCapacity": null,
        "volunteerCount": null
      },
      {
        "id": 333,
        "facilityType": "shelter",
        "status": 0,
        "name": "test shelter 3",
        "organizationId": null,
        "phone": "(620) 221-9664",
        "website": null,
        "city": "Winfield",
        "state": "KS",
        "county": "Cowley",
        "country": "usa",
        "zipCode": "67156",
        "latitude": 37.16481,
        "longitude": -97.026717,
        "privateAddress": false,
        "beds": 0,
        "baths": null,
        "favorite": null,
        "accreditations": [],
        "images": [],
        "distance": 11.4821168240232,
        "residentServed": "POP_UNDER_18,POP_18_65,POP_FEMALE_ONLY,POP_MALE_ONLY",
        "genderType": null,
        "acceptsInsurance": true,
        "avgCostMinimum": null,
        "depositAmount": null,
        "rentPaidWeekly": null,
        "moudMedications": null,
        "smokingPolicy": "PT_TOBACCO_ALLOWED_DESIGNATED",
        "bedUpdatedAt": null,
        "structureType": null,
        "volunteerNeeded": false,
        "volunteerCapacity": null,
        "volunteerCount": null
      },
      {
        "id": 333,
        "facilityType": "shelter",
        "status": 0,
        "name": "test shelter 4",
        "organizationId": null,
        "phone": "(620) 221-9664",
        "website": null,
        "city": "Winfield",
        "state": "KS",
        "county": "Cowley",
        "country": "usa",
        "zipCode": "67156",
        "latitude": 37.16481,
        "longitude": -97.026717,
        "privateAddress": false,
        "beds": 0,
        "baths": null,
        "favorite": null,
        "accreditations": [],
        "images": [],
        "distance": 11.4821168240232,
        "residentServed": "POP_UNDER_18,POP_18_65,POP_FEMALE_ONLY,POP_MALE_ONLY",
        "genderType": null,
        "acceptsInsurance": true,
        "avgCostMinimum": null,
        "depositAmount": null,
        "rentPaidWeekly": null,
        "moudMedications": null,
        "smokingPolicy": "PT_TOBACCO_ALLOWED_DESIGNATED",
        "bedUpdatedAt": null,
        "structureType": null,
        "volunteerNeeded": false,
        "volunteerCapacity": null,
        "volunteerCount": null
      },
    ]
  };
  